### ISSUE TITLE
安装xaop时报错

### ISSUE THREAD

**Issue by yanzi1** [liqiongfan/xaop#1]
![xaop](https://user-images.githubusercontent.com/41987492/50323555-27b2eb80-0515-11e9-91a6-95ae8f64c8b3.png)

**Comment by liqiongfan** [comment]
感谢你的使用，这边提示的问题在于您的PHP版本不是PHP7.1或者以上的版本，因此不支持扩展。需要更新您的php版本到php7.1以及以上版本才可以。
