### ISSUE TITLE
PHP7.2.6

### ISSUE THREAD

**Issue by xavieryang007** [liqiongfan/xaop#2]
安装扩展后Segmentation fault (core dumped)

**Comment by xavieryang007** [comment]
GDB 调试错误信息

0x00007ffff1a53b17 in zm_startup_xaop (type=<optimized out>, module_number=<optimized out>) at /mnt/e/code/php/xaop/xaop.c:102
102         XAOP_G(std_reader) = std_object_handlers.read_property;

**Comment by liqiongfan** [comment]
好的。感谢你的issue。麻烦提供下PHP具体版本信息，如：PHP 7.2.6 ZTS 或者 PHP7.2.5 NTS方便进行版本的追踪与修复.

**Comment by xavieryang007** [comment]
PHP 7.2.6 (cli) (built: Aug 11 2018 11:32:10) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by xavieryang007** [comment]
ubuntu 18.04

**Comment by liqiongfan** [comment]
好的。谢谢。祝您新年快乐。

**Comment by xavieryang007** [comment]
新年快乐

**Comment by liqiongfan** [comment]
![image](https://user-images.githubusercontent.com/10524832/52621507-6a27f180-2ee2-11e9-9d5d-43ff6d33d1e5.png)
![image](https://user-images.githubusercontent.com/10524832/52621515-70b66900-2ee2-11e9-95d5-e97be56b6602.png)
您好，我这边正常安装的PHP都是可以使用的，麻烦提供下您启用的其他扩展信息，目前有一个扩展(apcu)冲突，正在解决。

**Comment by xavieryang007** [comment]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
gettext
hash
iconv
inotify
intl
json
jwt
libxml
mbstring
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
swoole
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
yar
zip
zlib


![image](https://user-images.githubusercontent.com/6174650/52621584-a4918e80-2ee2-11e9-8a65-5c2d1348fc92.png)

**Comment by liqiongfan** [comment]
您停用一下 swoole看下。

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52621753-0baf4300-2ee3-11e9-84be-1a19c7bcbbf4.png)
停用这些后还是不行

**Comment by liqiongfan** [comment]
好的，谢谢。这边正在排查。

**Comment by xavieryang007** [comment]
多谢

**Comment by liqiongfan** [comment]
我这边安装了除了swoole与yar扩展外的其他扩展后，没有发现您说的情况，您这边是不是安装了扩展后，就报错？

**Comment by xavieryang007** [comment]
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/includ                                                                               e/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-zts-20170718
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... yes
checking for re2c... re2c
checking for re2c version... 1.0.1 (ok)
checking for gawk... gawk
checking whether to enable xaop support... yes, shared
checking for ld used by cc... /usr/bin/x86_64-linux-gnu-ld
checking if the linker (/usr/bin/x86_64-linux-gnu-ld) is GNU ld... yes
checking for /usr/bin/x86_64-linux-gnu-ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/xaop.c -o xaop.lo
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/kernel/exec.c -o kernel/exec.lo
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/kernel/helper.c -o kernel/helper.lo
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/kernel/parsing.c -o kernel/parsing.lo
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/kernel/classes.c -o kernel/classes.lo
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/kernel/annotations/annotation.c -o kernel/annotations/annotation.lo
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/kernel/xaop.c -o kernel/xaop.lo
/bin/bash /mnt/e/code/php/xaop/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/                                                                               php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/i                                                                               nclude/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2                                                                                  -c /mnt/e/code/php/xaop/kernel/interface/annotation.c -o kernel/interface/annotation.lo
mkdir kernel/.libs
mkdir kernel/.libs
mkdir kernel/.libs
mkdir .libs
mkdir kernel/interface/.libs
mkdir: cannot create directory 'kernel/.libs': File exists
mkdir: cannot create directory 'kernel/.libs': File exists
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/kernel/exec.c  -fPIC -DPIC -o                                                                                kernel/.libs/exec.o
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/kernel/xaop.c  -fPIC -DPIC -o                                                                                kernel/.libs/xaop.o
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/kernel/parsing.c  -fPIC -DPIC                                                                                -o kernel/.libs/parsing.o
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/kernel/helper.c  -fPIC -DPIC -                                                                               o kernel/.libs/helper.o
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/xaop.c  -fPIC -DPIC -o .libs/x                                                                               aop.o
mkdir kernel/annotations/.libs
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/kernel/classes.c  -fPIC -DPIC                                                                                -o kernel/.libs/classes.o
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/kernel/interface/annotation.c                                                                                 -fPIC -DPIC -o kernel/interface/.libs/annotation.o
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/mnt/e/code/php/xaop -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e                                                                               /code/php/xaop -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/                                                                               usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /mnt/e/code/php/xaop/kernel/annotations/annotation.                                                                               c  -fPIC -DPIC -o kernel/annotations/.libs/annotation.o
/bin/bash /mnt/e/code/php/xaop/libtool --mode=link cc -DPHP_ATOM_INC -I/mnt/e/code/php/xaop/include -I/mnt/e/code/php/xaop/main -I/mnt/e/code/php/xao                                                                               p -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php                                                                               /include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -o xaop.la -export-dynamic -avoid-version -prefer-pic -module -                                                                               rpath /mnt/e/code/php/xaop/modules  xaop.lo kernel/exec.lo kernel/helper.lo kernel/parsing.lo kernel/classes.lo kernel/annotations/annotation.lo kern                                                                               el/xaop.lo kernel/interface/annotation.lo
cc -shared  .libs/xaop.o kernel/.libs/exec.o kernel/.libs/helper.o kernel/.libs/parsing.o kernel/.libs/classes.o kernel/annotations/.libs/annotation.                                                                               o kernel/.libs/xaop.o kernel/interface/.libs/annotation.o   -Wl,-soname -Wl,xaop.so -o .libs/xaop.so
creating xaop.la
(cd .libs && rm -f xaop.la && ln -s ../xaop.la xaop.la)
/bin/bash /mnt/e/code/php/xaop/libtool --mode=install cp ./xaop.la /mnt/e/code/php/xaop/modules
cp ./.libs/xaop.so /mnt/e/code/php/xaop/modules/xaop.so
cp ./.libs/xaop.lai /mnt/e/code/php/xaop/modules/xaop.la
PATH="$PATH:/sbin" ldconfig -n /mnt/e/code/php/xaop/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /mnt/e/code/php/xaop/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/local/php/lib/php/extensions/no-debug-zts-20170718/
Configurations!!! you have installed the Xaop extension in PHP7.x
Please restart the webserver(Nginx|Apache) to use the new features!

**Comment by xavieryang007** [comment]
以上是编译过程

**Comment by xavieryang007** [comment]
开启xaop扩展之后就会报错

**Comment by xavieryang007** [comment]
系统采用的是WIN10 子系统ubuntu

**Comment by xavieryang007** [comment]
我用的是lnmp一键安装包安装的PHP

**Comment by liqiongfan** [comment]
好的，刚刚在忙，抱歉。

**Comment by liqiongfan** [comment]
josin@debian:/usr/local/php_7_2_6/bin$ ./php -v
PHP 7.2.6 (cli) (built: Feb 12 2019 16:14:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
josin@debian:/usr/local/php_7_2_6/bin$ ./php -m
[PHP Modules]
bcmath
bz2
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
SPL
sqlite3
standard
sysvsem
tokenizer
xaop
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]

您好，我这边安装了多个版本的PHP7.2.6之后，开启了多个扩展，然后使用xaop没有出现问题的。
您这边能否配合下，帮忙看下是哪个扩展冲突问题吗？
您下载的xaop是最新的代码吗？

**Comment by xavieryang007** [comment]
最新的

**Comment by xavieryang007** [comment]
我测试一下

**Comment by liqiongfan** [comment]
我找到问题了，正在解决。

**Comment by liqiongfan** [comment]
已经解决，麻烦您拉取下新代码。谢谢

**Comment by xavieryang007** [comment]
好的

**Comment by xavieryang007** [comment]
OK了

**Comment by liqiongfan** [comment]
已经可以了吗？

**Comment by xavieryang007** [comment]
可以了

**Comment by liqiongfan** [comment]
好的
