### ISSUE TITLE
注解模式不起作用

### ISSUE THREAD

**Issue by xavieryang007** [liqiongfan/xaop#3]
![image](https://user-images.githubusercontent.com/6174650/52691615-5214a880-2f9c-11e9-9d43-3695fc2d9e0a.png)

```php
<?php
/**
 * Powered by Xaop.
 * Xaop is an High performance PHP extension for WEB develop based on server such as Nginx/Apache
 * User can use, modify, copy Xan only when keep the explain words
 * https://www.supjos.cn All Rights Reserved.
 * License: BSD
 * User: Josin
 * Date: 2018/9/17
 */

/**
 * Class Swing
 * What you are doing were what you want.
 *
 *@Aspect
 */
class Swing
{
    function _magicGetBefore() {
        echo '_magicGetBefore()' . PHP_EOL;
    }

    function _magicGetAfter() {
        echo '_magicGetAfter()' . PHP_EOL;
    }

    function _magicSuccess() {
        echo '_magicSuccess()' . PHP_EOL;
    }

    function _magicFailure() {
        echo '_magicFailure()' . PHP_EOL;
    }

    /**
     * This is the __get magic function to do some magic
     * job.
     *@before( value="Swing._magicGetBefore" )
     *@after( value="Swing._magicGetAfter" )
     *@success( value="Swing._magicSuccess" )
     */
    public function __get($name)
    {
        echo '__get' . PHP_EOL;
        return true;
    }


    /**
     *@before( value="Swing._magicGetBefore" )
     *@after( value="Swing._magicGetAfter" )
     *@failure( value="Swing._magicFailure" )
     */
    public function __set($name, $value)
    {
        echo '__set' . PHP_EOL;
        return false;
    }

}

// echo '<pre>';

$swing = new Swing();

echo 'SET start' . PHP_EOL;

$swing->di = "di";

echo 'GET start' . PHP_EOL;

$swing->di;

// echo '</pre>';




```

只会打印如下
![image](https://user-images.githubusercontent.com/6174650/52691639-69539600-2f9c-11e9-9bfa-9c8d2f71bd94.png)

**Comment by liqiongfan** [comment]
![image](https://user-images.githubusercontent.com/10524832/52693626-2b597080-2fa2-11e9-9665-b9d598a9e828.png)
我这边生效的，php.ini配置如下：
![image](https://user-images.githubusercontent.com/10524832/52693644-390ef600-2fa2-11e9-8eab-d409832ab1c5.png)

**Comment by xavieryang007** [comment]
和你的配置一样

![image](https://user-images.githubusercontent.com/6174650/52693717-796e7400-2fa2-11e9-870f-dc5fd014e7d0.png)
![image](https://user-images.githubusercontent.com/6174650/52693721-7f645500-2fa2-11e9-9428-3525bdb30ee2.png)

**Comment by liqiongfan** [comment]
你的php只安装了这个版本吗？

**Comment by xavieryang007** [comment]
扩展是今天拉取的最新的代码生成的

**Comment by liqiongfan** [comment]
您在机器上php只安装了一个版本的php吗？

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52693824-cfdbb280-2fa2-11e9-96d7-46e29c9035d6.png)

**Comment by liqiongfan** [comment]
![image](https://user-images.githubusercontent.com/10524832/52693849-dd913800-2fa2-11e9-8e22-7ad2889e299a.png)
您执行下php看下是哪个php？

**Comment by xavieryang007** [comment]
只有一个版本的PHP ，因为WIN10 wsl编译PHP源码很慢，安装一个就够累了

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52693878-f4378f00-2fa2-11e9-87ea-2df333481f20.png)

**Comment by xavieryang007** [comment]
lnmp 一键安装包安装的

**Comment by liqiongfan** [comment]
您执行下面的命令看下输出：
php -i | grep xaop

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52693941-26e18780-2fa3-11e9-9324-cc8d41318536.png)

**Comment by xavieryang007** [comment]
系统WIN10 子系统ubuntu 18.04

**Comment by liqiongfan** [comment]
直接执行下源码目录下的demos文件夹下的第一个demo文件看下

**Comment by liqiongfan** [comment]
![image](https://user-images.githubusercontent.com/10524832/52694280-11209200-2fa4-11e9-80b8-563c5af26a97.png)

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52694309-2ac1d980-2fa4-11e9-8f68-129641c973aa.png)

但是直接拷贝到VSCODE 当中保存以后就不管用了

**Comment by liqiongfan** [comment]
应该是注解的样式变更了。注意，编写注解的时候要注意换行符，你自己编写一个demo试试。

**Comment by xavieryang007** [comment]
换行符是哪种的？是Unix？

**Comment by liqiongfan** [comment]
是的，仅支持Linux格式换行符模式，不支持Windows模式换行符

**Comment by xavieryang007** [comment]
解决了  是换行符的问题 是否应该兼容一下windows换行符，比较大多数程序员还是windows开发，有时候互相发下文件就变了

**Comment by liqiongfan** [comment]
因为这个是Linux系统或者Mac系统使用，Windows系统上没有这个扩展，所以当时就没有考虑过

**Comment by liqiongfan** [comment]
可以的，后面加上支持

**Comment by xavieryang007** [comment]
恩  多谢

**Comment by liqiongfan** [comment]
不客气

**Comment by liqiongfan** [comment]
您好，现在已经支持Windows格式的注解，请拉取最新代码，感谢使用。

**Comment by xavieryang007** [comment]
您好，完美

**Comment by xavieryang007** [comment]
已经都正常了，三克油

**Comment by liqiongfan** [comment]
好的，不客气
