### ISSUE TITLE
当方法不存在时段错误

### ISSUE THREAD

**Issue by xavieryang007** [liqiongfan/xaop#4]
@before(value="app\index\controller\Test.indexs" ) 如果Test类或Test类下不存在indexs 则会报段错误

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52757534-f56ac980-303f-11e9-9f97-1493205dfa9d.png)

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52757573-17644c00-3040-11e9-9699-db9753c12e95.png)
gdb调试后会出现上述错误信息

**Comment by liqiongfan** [comment]
这个能否把您的代码上传到这里，我这边调试的时候暂无法复现这个问题。

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/52759370-8e9cde80-3046-11e9-8bea-142c06635acc.png)

**Comment by xavieryang007** [comment]
代码已经发QQ

启动方法 进入bin目录 执行 php server.php  需要安装swoole扩展

**Comment by liqiongfan** [comment]
额，能否发邮件，QQ我一般都是在手机上查看，电脑我不喜欢使用Wine虚拟Windows软件，我工作电脑是Debian主机。麻烦发下邮件： xeapplee@gmail.com 或者 774542602@qq.com
