### ISSUE TITLE
注解success 建议

### ISSUE THREAD

**Issue by xavieryang007** [liqiongfan/xaop#6]
当方法返回true时调用success，PHP为脚本语言，调用方法经常会返回一些数据，而不仅仅是true，而是和true等价的不为假的数据。是否应该支持只要返回不为null,空,false 则为success

**Comment by liqiongfan** [comment]
您好，这个建议可以的。

**Comment by liqiongfan** [comment]
您好，拉取最新代码看下这个功能是否生效？

**Comment by xavieryang007** [comment]
恩 测试过了！是这样
